### ISSUE TITLE
WebGui's device set options not refreshing correctly

### ISSUE THREAD

**Issue by MathGaron** [lvsn/CameraNetwork#15] opened 2014-11-03 15:15 UTC
Reproduce bug : 
-Connect more than 1 device to the network.
-Go in Device pane in the webgui.
-select the first device
-once options are loaded, select a second device
The options are refreshed but the old one are not removed, so options stack up in the combobox

**Comment by soravux** [comment] 2014-11-05 16:39
The problem is the same as #14. I suggest we merge both issues together (unless there's more to this that I haven't seen?)

**Comment by MathGaron** [comment] 2014-11-05 18:42
maybe the explanation was not good. The combobox that enumerate the option to set camera's shutterspeed etc, seems to stack up, but it have nothing to do with camera names, in fact its probably only that the function that refresh the combobox dont erase the old options when we change camera.

**Comment by soravux** [comment] 2014-11-05 18:53
Oh boy, I effectively read that waaaaaay wrong! Sorry, was trying to do 2000 things at the same time! :) This is a matter of calling clear() in javascript, it won't be long to fix.

**Comment by soravux** [comment] 2014-11-05 21:49
Should be fixed in 9ec2fc6cbd5572ca252190f0077cb600535d64a4. (I have no cameras to test as of right now, can you confirm?)

**Comment by soravux** [comment] 2014-11-06 15:23
I forgot to clean the imageformat select. It's fixed in 665b3fe5de27513097f5a14d465c361803e33331 .

**Closed as completed by soravux** 2014-11-06 15:23 UTC
Labels: bug
