### ISSUE TITLE
Camera name stays in the webGUI page.

### ISSUE THREAD

**Issue by jacenfox** [lvsn/CameraNetwork#14] opened 2014-11-01 00:04 UTC
The cameras name, ObjCam and SkyCam, are always in the title of WebGUI. When shutdown the system without click the 'shutdown' button the the device page.

**Comment by soravux** [comment] 2014-11-01 16:40
You're right. The problem is, not only the web interface but also ROS thinks the cameras are still there. This is because the ROS master haven't received an active disconnect event from the cameras.

This would be fixed by having a heartbeat to ping the cameras and to timeout the cameras that doesn't answer.

**Comment by MathGaron** [comment] 2014-12-08 02:40
A thread in the server ping every address in IP param Server, if one dont answer after 2 seconds, the server remove it from the list

**Closed as completed by MathGaron** 2014-12-08 02:40 UTC
Labels: bug
